### ISSUE TITLE
data-val-required allows spaces

### ISSUE THREAD

**Issue by DaltonKirk** [chrisjwarnes/form-validator#1]
Hi Chris,

I have an input with the data-val-required data attribute on it. If I enter one or more spaces with no other characters it passes validation. I think that this should fail.

Thanks 😃

**Comment by DaltonKirk** [comment]
Maybe I'll have to use a regex pattern instead

**Comment by chrisjwarnes** [comment]
@DaltonKirk  thanks for this, yes you are right, it should trim the input before it validates, this has been fixed in version 1.0.14
