### ISSUE TITLE
Checkbox validation not working

### ISSUE THREAD

**Issue by karlisfeldmanis** [chrisjwarnes/form-validator#2]
input data-val="true" data-val-required="There are errors in this field" type="checkbox" name="rules"

Did not find information how to add AddRule for checkboxes...

**Comment by karlisfeldmanis** [comment]
I had a problem where I needed to use the reverse logic. Specifically, I wanted to check if the user had not checked a checkbox, and if so, add an error class.

**Comment by chriswarnescrafted** [comment]
@karlisfeldmanis this is possible, you would need to write a custom validation rule, i would take the required rule as a starting point.

for example  you could create something like this:

```
  addRule('valUnchecked', function (field) {
    return {
          type: 'boolean',
          required: true,
          message: field.dataset.valRequired,
          validator: (rule, value) => !field.checked
        }
    }
```

I'll put some time aside for updating the docs with some radio/checkbox examples.

Thanks,

**Comment by karlisfeldmanis** [comment]
Overall, great work!
